# Generated by Django 4.0.4 on 2022-05-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc_help',
            field=models.TextField(default='', max_length=170),
        ),
    ]
